name: Build and Publish NuGet

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x

    - name: Build and Pack
      run: make pack

    - name: Publish
      run: dotnet nuget push ./artifacts/*.nupkg -k ${NUGET_API_KEY} -s "https://nuget.pkg.github.com/MuehlbergTech/index.json" --skip-duplicate
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}