name: Build and Publish NuGet

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.0'

    - name: Build and Pack
      run: make pack

    - name: Publish
      run: make publish
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}